#!/usr/bin/env bash
#
# strands-pg installer — shadcn-style: we copy files into your new agent
# directory, then get out of your way. No pip install, no runtime dep on
# this repo.
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/peterb154/strands-pgsql-agent-framework/main/install.sh \
#     | bash -s -- my-agent
#
#   # Pin a specific version:
#   curl -sSL https://raw.githubusercontent.com/peterb154/strands-pgsql-agent-framework/v0.1.0/install.sh \
#     | bash -s -- my-agent --ref v0.1.0
#
#   # Paranoid mode (recommended for first-time users):
#   curl -sSL https://raw.githubusercontent.com/peterb154/strands-pgsql-agent-framework/main/install.sh -o install.sh
#   less install.sh   # read it before you run it
#   bash install.sh my-agent
#
# Env overrides:
#   STRANDS_PG_REPO  default: peterb154/strands-pgsql-agent-framework
#   STRANDS_PG_REF   default: latest git tag, or main if no tags exist

set -euo pipefail

REPO="${STRANDS_PG_REPO:-peterb154/strands-pgsql-agent-framework}"
REF="${STRANDS_PG_REF:-}"
TARGET=""
FORCE=false

usage() {
    cat <<EOF
Usage: install.sh <target-dir> [--ref <git-tag-or-branch>] [--force]

Options:
  --ref <ref>    Git tag or branch to install from (default: latest tag, else main)
  --force, -f    Stamp into an existing directory (overlay; won't delete unrelated files)
  -h, --help     Show this help

Examples:
  install.sh my-agent
  install.sh my-agent --ref v0.1.0
  install.sh existing-repo --force --ref main    # re-stamp an existing dir in place
  STRANDS_PG_REF=main install.sh my-agent
EOF
}

# ---- arg parse ------------------------------------------------------------

while (( $# )); do
    case "$1" in
        -h|--help) usage; exit 0 ;;
        --ref)
            REF="$2"
            shift 2
            ;;
        --ref=*)
            REF="${1#--ref=}"
            shift
            ;;
        -f|--force)
            FORCE=true
            shift
            ;;
        -*)
            echo "unknown flag: $1" >&2
            usage
            exit 2
            ;;
        *)
            if [[ -z "$TARGET" ]]; then
                TARGET="$1"
            else
                echo "too many positional args: $1" >&2
                usage
                exit 2
            fi
            shift
            ;;
    esac
done

if [[ -z "$TARGET" ]]; then
    echo "error: target directory is required" >&2
    usage
    exit 2
fi

if [[ -e "$TARGET" ]] && [[ "$FORCE" != "true" ]]; then
    echo "error: $TARGET already exists — pick a new path, remove it first, or pass --force to overlay" >&2
    exit 1
fi

if [[ -e "$TARGET" ]] && [[ "$FORCE" == "true" ]]; then
    echo "==> --force: stamping into existing directory $TARGET (overlay, no delete)"
fi

# ---- resolve ref ----------------------------------------------------------

if [[ -z "$REF" ]]; then
    echo "==> resolving latest release tag for $REPO..."
    # Ask GitHub's git endpoint for tags sorted by version. No auth required.
    REF="$(git ls-remote --tags --refs "https://github.com/${REPO}.git" \
              | awk -F/ '{print $NF}' \
              | sort -V \
              | tail -1 || true)"
    if [[ -z "$REF" ]]; then
        echo "    no tags found — falling back to main"
        REF="main"
    else
        echo "    using $REF"
    fi
fi

# ---- fetch ----------------------------------------------------------------

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "==> cloning ${REPO}@${REF}..."
if ! git clone --quiet --depth=1 --branch="$REF" "https://github.com/${REPO}.git" "$TMP/src" 2>/dev/null; then
    echo "error: failed to clone ${REPO}@${REF}" >&2
    echo "  check the ref exists: https://github.com/${REPO}/tree/${REF}" >&2
    exit 1
fi

# ---- stamp ----------------------------------------------------------------

echo "==> stamping into $TARGET..."
mkdir -p "$TARGET"

# Template files (Dockerfile, compose, app.py, prompts, etc.) — the shape of
# the new agent.
cp -R "$TMP/src/templates/agent/." "$TARGET/"

# Vendored framework source — user owns this now.
mkdir -p "$TARGET/strands_pg"
cp -R "$TMP/src/src/strands_pg/." "$TARGET/strands_pg/"

# Framework migrations 001-099. User drops their own 100+ next to these.
mkdir -p "$TARGET/migrations"
cp -R "$TMP/src/migrations/." "$TARGET/migrations/"

# Convenience: create an empty tools/ so imports don't blow up.
mkdir -p "$TARGET/tools"
touch "$TARGET/tools/__init__.py"

# Clean up the .gitkeep if we left it.
rm -f "$TARGET/tools/.gitkeep"

# Record the stamp reference so `diff -r` later has something to compare to.
cat > "$TARGET/.strands-pg-ref" <<EOF
# Generated by install.sh; shows which upstream ref this agent was stamped from.
# Safe to commit or delete — it's purely informational.
repo=${REPO}
ref=${REF}
stamped_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF

# ---- finish ---------------------------------------------------------------

cat <<EOF

==> stamped from ${REPO}@${REF} into $TARGET

next steps:
  cd $TARGET
  cp .env.example .env
  # edit .env: set AWS_PROFILE to one with Bedrock access
  docker compose up --build

  # in another shell:
  curl -s localhost:8000/health
  curl -sX POST localhost:8000/chat \\
    -H 'content-type: application/json' \\
    -d '{"session_id":"you@example.com","message":"hello"}'

read $TARGET/README.md for what to edit next.
EOF
